(define-key global-map (kbd "C-q") 'nil)
(define-key global-map (kbd "C-q c") 'avy-copy-line)
(define-key global-map (kbd "C-q g") 'goto-line)
(define-key global-map (kbd "C-q k") 'kill-other-buffers)
(define-key global-map (kbd "C-q r") 'anzu-query-replace)
(define-key global-map (kbd "C-q C-r") 'anzu-query-replace-regexp)
(define-key global-map (kbd "C-q C-M-r") 'anzu-query-replace-at-cursor-thing)
(define-key global-map (kbd "C-q d") 'delete-trailing-whitespace)
(global-set-key (kbd "C-q o") 'helm-recentf)
(global-set-key (kbd "C-q i") (lambda () (interactive) (switch-to-buffer (find-file-noselect "~/.emacs.d/init.el")))) ; init.elを開く
(define-key global-map (kbd "C-q t") 'toggle-truncate-lines)
